### PR TITLE
Fix: Proposal page error handling

### LINKED ISSUE #243: [BUG] When the gov ui is open for a while it errors out
in order to reproduce, open the governance ui and leave it open for a while it will render an error, console shows "ChainNotConfiguredError".
might be related to ddos protection of vercel but requires further investigation

### PR DESCRIPTION
**Pull request by denviljclarke**
### Description

This PR fixes an issue where the proposal page crashes randomly, often after some time on the page. This crashing behavior was caused by an error thrown within an external library. Three main things contributed to this. 

- The library we were using to query the graph (Apollo) threw an unhandled error in the proposal fetching hook
- We didn't have a global error page to catch these unhandled errors
- We were polling the graph too many times, which caused the graph to throttle us

I've added an error page to catch any unhandled errors like this & made changes to poll less & read from the cache more often. We should also look at our subgraph to see if we can increase the request limit

**For Reviewers**

You can replicate the error by visiting the [governance site](https://governance.mento.org) & opening several tabs, which will result in a crash. When you visit the deployment for this fix and perform the same test, we shouldn't have that problem now. There's also a button at the bottom of the proposal page which you can use to trigger an error to have a look at the error page, once this is reviewed we'll remove it before we merge this.

### Other changes

Added a global error page to help users reset the app instead of the black crash screen that was displayed before

### Tested

I opened several tabs on the preview and didn't experience a crash.

### Related issues

- Fixes #243

### CODE REVIEW

File: src/app/proposals/[id]/page.tsx [hunk 1]
```diff
@@ -297,8 +298,31 @@ const Page = ({ params: { id } }: { params: { id: string } }) => {
           </div>
         </div>
       </main>
+      <ErrorTest />
```
Comment (RyRy79261) [inline src/app/proposals/[id]/page.tsx:301]: Just need to remove this before merging

**Comment by Andrew718PLTS** [comment]
The issue resolving looks good to me.
Besides testing the main issue resolving, I've found another issue, but I guess it's not related to exactly this PR (let me know if you think we need to create a separate one - I'll). There is no file to download or open by clicking on the "Cookie Policy" button. (as far I as see we try to download it but I'd suggest to open it with a specific route as we do with the Policy button)
(on the prod same behaviour)
image

File: src/app/error.tsx [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+  return (
+    <html>
+      <body className="flex h-screen flex-col items-center justify-center gap-12 dark:bg-black">
+        <div className="flex flex-col items-center justify-center">
+          <h1 className="font-fg text-7xl font-bold">Error</h1>
+          <p className="font-fg text-3xl">Oops, something went wrong!</p>
+        </div>
+        <Button
+          onClick={() => {
+            if (isHome) {
```
Comment (Andrew718PLTS) [inline src/app/error.tsx:32]: There are only two lines to do something differently - I'd suggest to use the ternary operator

File: src/app/error.tsx [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+import { Button } from "@/components/_shared";
+import { links } from "@/lib/constants/links";
+import * as Sentry from "@sentry/nextjs";
+import { usePathname } from "next/navigation";
+import { useEffect } from "react";
+
+export default function Error({
+  error,
+  reset,
+}: {
```
Comment (Andrew718PLTS) [inline src/app/error.tsx:12]: You're using the same interface for a returning type - I'd suggest to create an interface and reuse for both cases. (second usage in the src/app/global-error.tsx 10 row)

File: src/app/proposals/[id]/page.tsx [hunk 4]
```diff
@@ -30,7 +30,7 @@ const ProposalCountdown = ({ proposal }: { proposal: Proposal }) => {
   });
 
   const endBlock = useBlock({
-    blockNumber: BigInt(proposal.endBlock),
+    blockNumber: proposal.endBlock ? BigInt(proposal.endBlock) : 0n,
```
[the remark this answers is not in the document]
Comment (denviljclarke) [reply src/app/proposals/[id]/page.tsx:33]: I'll add it for some consistency, but we'll always have a proposal if this is rendered because of the early return on line 129 when we don't have a proposal

File: src/app/proposals/[id]/page.tsx (hunk 1 above)
Comment (denviljclarke) [reply src/app/proposals/[id]/page.tsx:301]: Will do, once all reviews are in

**Review by baroooo — APPROVED** [review]

**Comment by denviljclarke** [comment]
> The issue resolving looks good to me. Besides testing the main issue resolving, I've found another issue, but I guess it's not related to exactly this PR (let me know if you think we need to create a separate one - I'll). There is no file to download or open by clicking on the "Cookie Policy" button - therefore, we're getting error. (as far I as see we try to download it but I'd suggest to open it with a specific route as we do with the Policy button) (on the prod same behaviour) image

 I found an issue for this which was closed because it's not needed. Will create an issue to clarify if it is & if it's not we'll remove the link in the footer
